version: '3'

services:
  postgres-for-sberic:
    image: postgres:latest
    container_name: sberic-pg
    ports:
      - '5432:5432'
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./postgres-db:/var/lib/postgresql/data

  python-for-sberic:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - '8000:8000'
    links:
      - postgres-for-sberic
    depends_on:
      - postgres-for-sberic


volumes:
  postgres-db:
