version: '3'

services:
  postgres-for-sberic:
    image: postgres:latest
    container_name: sberic-pg
    ports:
      - '5432:5432'
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./postgres-db:/var/lib/postgresql/data

#  python-for-kotlin:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    restart: on-failure
#    ports:
#      - '1337:1337'
#    links:
#      - postgres-for-kotlin
#    depends_on:
#      - postgres-for-kotlin


volumes:
  postgres-db:
